from ability_list import abilities
from moves_list import moves

pokemon = [{
        'name' : 'greninja',
        'type' : ['water', 'dark'],#both of these
        'abilities' : [abilities['torrent'], abilities['protean']],#one of these
        'moves' : [moves['night_slash'], moves['role_play'], moves['mat_block'],
            moves['pound'], moves['growl'], moves['bubble'],
            moves['quick_attack'], moves['lick'], moves['water_pulse'],
            moves['smokescreen'], moves['shadow_sneak'], moves['spikes'],
            moves['feint_attack'], moves['water_shuriken'], moves['substitute'],
            moves['extrasensory'], moves['double_team'], moves['haze'],
            moves['hydro_pump'], moves['toxic'], moves['hidden_power'],
            moves['taunt'], moves['ice_beam'], moves['blizzard'],
            moves['hyper_beam'], moves['protect'], moves['rain_dance'],
            moves['frustration'], moves['smack_down'], moves['return'],
            moves['dig'], moves['double_team'], moves['rock_tomb'],
            moves['aerial_ace'], moves['facade'], moves['rest'],
            moves['attract'], moves['thief'], moves['round'],
            moves['echoed_voice'], moves['scald'], moves['fling'],
            moves['acrobatics'], moves['giga_impact'], moves['rock_slide'],
            moves['grass_knot'], moves['swagger'], moves['sleep_talk'],
            moves['u-turn'], moves['rock_smash'], moves['dark_pulse'],
            moves['power-up_punch'], moves['confide'], moves['cut'],
            moves['surf'], moves['strength'], moves['waterfall'],
            moves['bestow'], moves['camouflage'], moves['mind_reader'],
            moves['mud_sport'], moves['toxic_spikes'], moves['water_sport'],
            moves['hydro_cannon'], moves['water_pledge'], moves['bounce']],#four of these
        'hp' : 73,
        'attack' : 95,
        'defense' : 67,
        'sp_atk' : 103,
        'sp_def' : 71,
        'speed' : 122
        }, {
        'name' : 'chesnaught',
        'type' : ['grass', 'fighting'],
        'abilities' : [abilities['overgrow'], abilities['protean']],
        'moves' : [moves['feint'], moves['tackle'], moves['growl'],
            moves['vine_whip'], moves['bite'], moves['leech_seed'],
            moves['pin_missle'], moves['needle_arm'], moves['take_down'],
            moves['seed_bomb'], moves['spiky_sheild'], moves['mud_shot'],
            moves['bulk_up'], moves['body_slam'], moves['pain_split'],
            moves['wood_hammer'], moves['hammer_arm'],
            moves['hone_claws'], moves['dragon_claw'], moves['roar'],
            moves['toxic'], moves['hidden_power'], moves['sunny_day'],
            moves['taunt'], moves['hyper_beam'], moves['protect'],
            moves['solar_beam'], moves['earthquake'], moves['return'],
            moves['dig'], moves['brick_break'], moves['double_team'],
            moves['reflect'], moves['smack_down'], moves['frustration'],
            moves['sludge_bomb'], moves['rock_tomb'], moves['aerial_ace'],
            moves['facade'], moves['rest'], moves['attract'],
            moves['low_sweep'], moves['round'], moves['focus_blast'],
            moves['energy_ball'], moves['fling'], moves['shadow_claw'],
            moves['payback'], moves['retaliate'],moves['giga_impact'],
            moves['flash'], moves['stone_edge'], moves['gyro_ball'],
            moves['swords_dance'], moves['bulldoze'], moves['rock_slide'],
            moves['poison_jab'], moves['grass_knot'], moves['swagger'],
            moves['sleep_talk'], moves['substitute'], moves['rock_smash'],
            moves['nature_power'], moves['power-up_punch'], moves['confide'],
            moves['cut'], moves['strength'], moves['belly_drum'],
            moves['curse'], moves['defense_curl'], moves['quick_guard'],
            moves['rollout'], moves['spikes'], moves['synthesis'],
            moves['frenzy_plant'], moves['grass_pledge']],
        'hp' : 88,
        'attack' : 107,
        'defense' : 122,
        'sp_atk' : 74,
        'sp_def': 75,
        'speed' : 64
        }]

